[package]
name = "modsync_core"
version = "0.2.2"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
serde = { version = "1.0.210", features = ["derive"] }
sqlx = { version = "0.8", features = [ "runtime-tokio", "tls-rustls-ring", "postgres", "macros" ] }

